import type { Metadata } from "next";
import { FinanceProvider } from "./context/FinanceContext";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FinanceProvider>
          <Navbar />
          {children}
          <Footer />
        </FinanceProvider>
      </body>
    </html>
  );
}
